services:
  php:
    image: php:8.2-fpm
    container_name: php-website
    volumes:
      - ./:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - forgottenserver-network

networks:
  forgottenserver-network:
    external: true
